export const quizConstants = {
  GETALL_REQUEST: 'QUIZ_GETALL_REQUEST',
  GETALL_SUCCESS: 'QUIZ_GETALL_SUCCESS',
  GETALL_FAILURE: 'QUIZ_GETALL_FAILURE',

  GET_REQUEST: 'QUIZ_GET_REQUEST',
  GET_SUCCESS: 'QUIZ_GET_SUCCESS',
  GET_FAILURE: 'QUIZ_GET_FAILURE',

  CREATE_REQUEST: 'QUIZ_CREATE_REQUEST',
  CREATE_SUCCESS: 'QUIZ_CREATE_SUCCESS',
  CREATE_FAILURE: 'QUIZ_CREATE_FAILURE',

  DELETE_REQUEST: 'QUIZ_DELETE_REQUEST',
  DELETE_SUCCESS: 'QUIZ_DELETE_SUCCESS',
  DELETE_FAILURE: 'QUIZ_DELETE_FAILURE',

  RESPONSE_REQUEST: 'QUIZ_RESPONSE_REQUEST',
  RESPONSE_SUCCESS: 'QUIZ_RESPONSE_SUCCESS',
  RESPONSE_FAILURE: 'QUIZ_RESPONSE_FAILURE',

  EMPTY_QUESTION: {
    name: '',
    option1: '',
    option2: '',
    option3: '',
    option4: '',
    correctAnswer: 1
  }
};